### ISSUE TITLE
GenerateEventFunction returns error

### ISSUE THREAD

**Issue by tofferf** [aws-samples/amazon-chime-live-events#11]
I ran deploy.js and uploaded my csv files to the appropriate s3 buckets.  When I try to invoke GenerateEventFunction I get the following error:
```
{
  "errorType": "MissingRequiredParameter",
  "errorMessage": "Missing required key 'Key' in params",
  "trace": [
    "MissingRequiredParameter: Missing required key 'Key' in params",
    "    at ParamValidator.fail (/var/task/node_modules/aws-sdk/lib/param_validator.js:50:37)",
    "    at ParamValidator.validateStructure (/var/task/node_modules/aws-sdk/lib/param_validator.js:61:14)",
    "    at ParamValidator.validateMember (/var/task/node_modules/aws-sdk/lib/param_validator.js:88:21)",
    "    at ParamValidator.validate (/var/task/node_modules/aws-sdk/lib/param_validator.js:34:10)",
    "    at Request.VALIDATE_PARAMETERS (/var/task/node_modules/aws-sdk/lib/event_listeners.js:126:42)",
    "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
    "    at callNextListener (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:96:12)",
    "    at /var/task/node_modules/aws-sdk/lib/event_listeners.js:86:9",
    "    at finish (/var/task/node_modules/aws-sdk/lib/config.js:386:7)",
    "    at /var/task/node_modules/aws-sdk/lib/config.js:404:9",
    "    at EnvironmentCredentials.get (/var/task/node_modules/aws-sdk/lib/credentials.js:127:7)",
    "    at getAsyncCredentials (/var/task/node_modules/aws-sdk/lib/config.js:398:24)",
    "    at Config.getCredentials (/var/task/node_modules/aws-sdk/lib/config.js:418:9)",
    "    at Request.VALIDATE_CREDENTIALS (/var/task/node_modules/aws-sdk/lib/event_listeners.js:81:26)",
    "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:102:18)",
    "    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)"
  ]
}
```

**Comment by tofferf** [comment]
@ziyiz-amzn are you able to duplicate this?

**Comment by ziyiz-amzn** [comment]
> @ziyiz-amzn are you able to duplicate this?

Taking a look, will update you soon.

**Comment by ziyiz-amzn** [comment]
> @ziyiz-amzn are you able to duplicate this?

Can you confirm that the csv file is formatted correctly? Could you provide us an example csv file?

**Comment by tofferf** [comment]
Attendees.csv:
```
full_name
Attendee1
Attendee2
Attendee3
Attendee4
Attendee5
Attendee6
Attendee7
Attendee8
Attendee9
Attendee10
Attendee11
Attendee12
Attendee13
Attendee14
Attendee15
Attendee16
Attendee17
Attendee18
Attendee19
```

Moderators.csv:
```
full_name
Moderator One
```

Talents.csv:
```
full_name
Talent One
```
