### ISSUE TITLE
Serverless backend deploy throws samtranslator.model.exceptions.InvalidDocumentException

### ISSUE THREAD

**Issue by realharry** [aws-samples/amazon-chime-live-events#16]
I tried deploying the backend (src/backend/serverless) following the README instructions, but ran into some kind of permission issues. I am not sure if it's specific to me or a general issue. The error happens at line 2054 of template.yml:

```
ApplicationId: arn:aws:serverlessrepo:us-east-1:375983427419:applications/deploy-to-s3
```

I'm not entirely sure what this account `375983427419` is.

Here's the error message:

```
Initiating deployment
=====================
,Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/samcli/lib/samlib/wrapper.py", line 76, in run_plugins
    parser.parse(template_copy, all_plugins)  # parse() will run all configured plugins
  File "/usr/local/lib/python3.8/dist-packages/samcli/lib/samlib/wrapper.py", line 145, in parse
    raise InvalidDocumentException(document_errors)
samtranslator.model.exceptions.InvalidDocumentException: [InvalidResourceException('SiteDeploymentLayer', 'User: arn:aws:iam::xxx:user/yyy is not authorized to perform: serverlessrepo:CreateCloudFormationTemplate on resource: arn:aws:serverlessrepo:us-east-1:375983427419:applications/deploy-to-s3')]
```

**Comment by realharry** [comment]
I am not very familiar with SAR (I've never used it), but the error seems a bit confusing. The error points out the permissions that don't even exist - https://docs.aws.amazon.com/serverlessrepo/latest/devguide/serverlessrepo-api-permissions-ref.html. Anyways, adding those permissions to the IAM user solved this particular issue. Still blocked with other errors, but at least this is no longer a problem. Closing the ticket.
